server:
#  注意这里的端口和服务提供者的不能是同一个端口
  port: 8082

Spring:
  application:
    name: microservice-customer-user
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
      instance:
        # prefer-ip-address:true表示将自己的服务注册到Eureka server上
        prefer-ip-address: true